// Knowledge base module — reads pre-built JSON (no fs dependency)
// The JSON is generated at build time by scripts/build-kb.js
import kbData from './kb-sections.json'

// Re-declare the type here to avoid circular imports with prompts.ts
type TipoAgente = 'general' | 'financiero' | 'ventas' | 'marketing' | 'rrhh' | 'inventario' | 'legal'

interface KBSection {
  title: string
  content: string
  keywords: string[]
}

// Cache parsed sections per agent
const sectionCache = new Map<TipoAgente, KBSection[]>()

/**
 * Extract searchable keywords from text.
 * Removes stop words, normalizes, and returns unique words.
 */
function extractKeywords(text: string): string[] {
  const stopWords = new Set([
    'el', 'la', 'los', 'las', 'un', 'una', 'unos', 'unas', 'de', 'del', 'al',
    'en', 'con', 'por', 'para', 'es', 'son', 'que', 'se', 'no', 'si', 'como',
    'más', 'pero', 'o', 'y', 'a', 'su', 'sus', 'este', 'esta', 'estos',
    'cada', 'todo', 'todos', 'muy', 'ya', 'hay', 'ser', 'tener', 'hacer',
    'poder', 'deber', 'ir', 'ver', 'dar', 'saber', 'querer', 'llegar',
    'the', 'is', 'are', 'of', 'and', 'to', 'in', 'for', 'on', 'with',
  ])

  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '') // Remove accents
    .replace(/[^a-z0-9\s]/g, ' ')
    .split(/\s+/)
    .filter(w => w.length > 2 && !stopWords.has(w))
    .filter((w, i, arr) => arr.indexOf(w) === i) // unique
}

/**
 * Score how relevant a section is to a query.
 * Uses keyword overlap + title matching.
 */
function scoreSection(section: KBSection, queryKeywords: string[]): number {
  let score = 0
  const sectionKeywords = new Set(section.keywords)

  for (const qk of queryKeywords) {
    if (sectionKeywords.has(qk)) {
      score += 1
    }
    // Partial match (prefix)
    for (const sk of sectionKeywords) {
      if (sk.startsWith(qk) || qk.startsWith(sk)) {
        score += 0.5
      }
    }
  }

  // Boost if query keywords appear in the title
  const titleLower = section.title.toLowerCase()
  for (const qk of queryKeywords) {
    if (titleLower.includes(qk)) {
      score += 3
    }
  }

  return score
}

/**
 * Load and cache knowledge base sections for an agent type.
 * Reads from pre-built JSON (generated by scripts/build-kb.js).
 */
function loadSections(agenteTipo: TipoAgente): KBSection[] {
  if (sectionCache.has(agenteTipo)) {
    return sectionCache.get(agenteTipo)!
  }

  const sections = (kbData as Record<string, KBSection[]>)[agenteTipo] || []
  sectionCache.set(agenteTipo, sections)
  return sections
}

/**
 * Retrieve the most relevant knowledge base sections for a user query.
 * Returns up to maxSections sections, each truncated to maxCharsPerSection.
 * Total output is capped at maxTotalChars to fit in context window.
 */
export function retrieveKnowledge(
  agenteTipo: TipoAgente,
  userMessage: string,
  conversationHistory: string = '',
  maxSections: number = 1,
  maxTotalChars: number = 1000
): string {
  const sections = loadSections(agenteTipo)
  if (sections.length === 0) return ''

  // Combine user message with recent conversation for better matching
  const fullQuery = userMessage + ' ' + conversationHistory.slice(-500)
  const queryKeywords = extractKeywords(fullQuery)

  if (queryKeywords.length === 0) return ''

  // Score and rank sections
  const scored = sections
    .map(section => ({ section, score: scoreSection(section, queryKeywords) }))
    .filter(s => s.score > 1) // Minimum relevance threshold
    .sort((a, b) => b.score - a.score)
    .slice(0, maxSections)

  if (scored.length === 0) return ''

  // Build knowledge context, respecting total char limit
  let result = '\n\nCONOCIMIENTO ESPECIALIZADO RELEVANTE:\n'
  let totalChars = result.length

  for (const { section } of scored) {
    const sectionText = `\n### ${section.title}\n${section.content}\n`
    if (totalChars + sectionText.length > maxTotalChars) {
      // Truncate this section to fit
      const remaining = maxTotalChars - totalChars - 50
      if (remaining > 200) {
        result += `\n### ${section.title}\n${section.content.substring(0, remaining)}...\n`
      }
      break
    }
    result += sectionText
    totalChars += sectionText.length
  }

  return result
}

/**
 * Get a general overview of the knowledge base for an agent.
 * Used for the first message to give the agent awareness of what it knows.
 */
export function getKBOverview(agenteTipo: TipoAgente): string {
  const sections = loadSections(agenteTipo)
  if (sections.length === 0) return ''

  const titles = sections.map(s => s.title).slice(0, 20)
  return `\nTu base de conocimiento incluye información detallada sobre:\n${titles.map(t => `• ${t}`).join('\n')}\nUsa este conocimiento cuando sea relevante para dar respuestas profundas y específicas.\n`
}
