-- Expansión de prospectos LATAM — Fase 2
-- +98 nuevos contactos (México +14, Colombia +22, Perú +20, Argentina +25, Uruguay +17)

INSERT INTO marketing_prospectos_latam (nombre, cargo_destinatario, email, pais, tipo, sitio_web, pymnes_aprox, notas) VALUES

-- ── MÉXICO ──
('Canaco CDMX', 'Atención Institucional', 'primercontacto@ccmexico.com.mx', 'MX', 'camara', 'ccmexico.com.mx', 80000, 'Cámara de Comercio de la Ciudad de México. Gran base empresarial PYME.'),
('CANACOPE CDMX', 'Presidencia', 'contacto@canacope.mx', 'MX', 'camara', 'canacopecdmx.com', 40000, 'Cámara Nacional de Comercio en Pequeño CDMX. Pequeño comercio formal.'),
('Cámara de Comercio de Guadalajara', 'Presidente Consejo Directivo', 'presidencia@camaradecomerciogdl.mx', 'MX', 'camara', 'camaradecomerciogdl.mx', 50000, 'Principal cámara comercial de Jalisco. Segunda ciudad de México.'),
('CANACO Monterrey', 'Director Ejecutivo', 'contacto@canaco.net', 'MX', 'camara', 'canaco.net', 45000, 'Cámara de Comercio de Nuevo León. Capital industrial del norte de México.'),
('CANACO Puebla', 'Presidencia', 'presidencia@canacopuebla.org.mx', 'MX', 'camara', 'canacopuebla.org.mx', 30000, 'Cámara de Comercio de Puebla. Cuarta ciudad más grande de México.'),
('CANACO Tijuana', 'Presidente', 'presidente@canacotijuana.com', 'MX', 'camara', 'canacotijuana.com', 20000, 'Cámara de Comercio Tijuana. Frontera con EE.UU., alta actividad comercial.'),
('CAINTRA Nuevo León', 'Relaciones Institucionales', 'address.general@caintra.org.mx', 'MX', 'gremio', 'caintra.org.mx', 15000, 'Cámara de la Industria de Transformación de Nuevo León. Foco industrial PYME.'),
('CAMESCOM', 'Directora General', 'cam.espanola@camescom.mx', 'MX', 'camara', 'camescom.mx', 5000, 'Cámara Española de Comercio en México. Red de empresas hispanomexicanas.'),
('TechBA / FUMEC', 'Dirección de Comunicación', 'comunicacion@techba.org', 'MX', 'aceleradora', 'techba.org', 0, 'Aceleradora tecnológica para PYMEs con proyección internacional.'),
('NAFIN — Análisis y Mercados', 'Director de Análisis y Promoción', 'agamboa@nafin.gob.mx', 'MX', 'gobierno', 'nafin.com', 0, 'Nacional Financiera. Principal banco de desarrollo para PYMEs en México.'),
('NAFIN — Ejecutivo PYMEs', 'Ejecutivo de Financiamiento', 'amartinez@nafin.gob.mx', 'MX', 'gobierno', 'nafin.com', 0, 'Contacto directo ejecutivo en NAFIN para programas PYME.'),
('Alto Nivel', 'Director de Contenidos', 'redaccion@altonivel.com.mx', 'MX', 'medio', 'altonivel.com.mx', 0, 'Revista de negocios y PYMEs. También cubre emprendedor.com (mismo grupo).'),
('Pymempresario', 'Dirección Editorial', 'administracion@pymempresario.com', 'MX', 'medio', 'pymempresario.com', 0, 'Portal especializado en PYMEs y emprendedores. Alta cobertura sectorial.'),
('CANACO Tijuana — Dirección', 'Director General', 'directorgral@canacotijuana.com', 'MX', 'camara', 'canacotijuana.com', 0, 'Director General de Cámara de Comercio Tijuana.'),

-- ── COLOMBIA ──
('Cámara de Comercio de Bogotá', 'Dirección de Gestión Empresarial', 'leytransparencia@ccb.org.co', 'CO', 'camara', 'ccb.org.co', 120000, 'CCB. La cámara de comercio más grande de Colombia. 120K+ empresas registradas.'),
('Cámara de Comercio de Medellín', 'Dirección de Competitividad', 'transparencia@camaramedellin.com.co', 'CO', 'camara', 'camaramedellin.com.co', 80000, 'Principal cámara de Antioquia. Medellín es hub de innovación LATAM.'),
('Cámara de Comercio de Cali', 'Vicepresidencia Empresarial', 'contacto@ccc.org.co', 'CO', 'camara', 'ccc.org.co', 60000, 'Cámara de Comercio de Cali. Tercera ciudad colombiana.'),
('Cámara de Comercio de Barranquilla', 'Dirección de Desarrollo Empresarial', 'ncarbonell@camarabaq.org.co', 'CO', 'camara', 'camarabaq.org.co', 45000, 'CCB. Principal cámara de la Costa Atlántica colombiana.'),
('Cámara de Comercio de Bucaramanga', 'Dirección de Competitividad', 'transparencia@camaradirecta.com', 'CO', 'camara', 'camaradirecta.com', 35000, 'Cámara de Bucaramanga. Santander es región industrial activa.'),
('Cámara de Comercio de Cartagena', 'Dirección de Servicios Empresariales', 'pqrs@cccartagena.org.co', 'CO', 'camara', 'cccartagena.org.co', 25000, 'Cámara de Cartagena. Polo turístico y comercial del Caribe.'),
('ANDI Colombia', 'Presidencia / Dirección Comercial', 'comercial@andi.com.co', 'CO', 'gremio', 'andi.com.co', 10000, 'Asociación Nacional de Empresarios de Colombia. Gremio más influyente del país.'),
('CAMACOL Colombia', 'Presidencia Ejecutiva', 'contactenos@camacol.org.co', 'CO', 'gremio', 'camacol.co', 8000, 'Cámara Colombiana de la Construcción. Fuerte base de PYMEs constructoras.'),
('FEDEGAN Colombia', 'Dirección PYMEs', 'pqrs@fedegan-fng.org.co', 'CO', 'gremio', 'fedegan.org.co', 15000, 'Federación Colombiana de Ganaderos. Red rural con PYMEs agropecuarias.'),
('ASOHOFRUCOL', 'Dirección Ejecutiva', 'contactenos@asohofrucol.com.co', 'CO', 'gremio', 'asohofrucol.com.co', 5000, 'Asociación Hortifrutícola de Colombia. Productores agrícolas PYME.'),
('Inexmoda Colombia', 'Dirección Ejecutiva', 'info@inexmoda.org.co', 'CO', 'gremio', 'inexmoda.org.co', 6000, 'Instituto para Exportación y la Moda. PYMEs del sector textil y moda.'),
('Ruta N Medellín', 'Dirección de Emprendimiento', 'visitas@rutanmedellin.org', 'CO', 'aceleradora', 'rutanmedellin.org', 0, 'Hub de innovación de Medellín. Referente de ecosistema tech en LATAM.'),
('BICTIA Colombia', 'Dirección de Aceleración', 'contacto@bictia.com', 'CO', 'aceleradora', 'bictia.com', 0, 'Aceleradora ProBogotá. Conecta startups con grandes empresas.'),
('Invest in Bogotá', 'Director de Ecosistema Emprendedor', 'info@investinbogota.org', 'CO', 'gobierno', 'investinbogota.org', 0, 'Agencia de promoción de inversión de Bogotá. Nexo con empresas internacionales.'),
('Invest Pacific Colombia', 'Dirección de Inversión Regional', 'info@investpacific.org', 'CO', 'gobierno', 'investpacific.org', 0, 'Agencia de inversión del Valle del Cauca. Región con alta concentración PYME.'),
('Fondo Nacional de Garantías', 'Subgerencia MiPymes', 'correspondencia@fng.gov.co', 'CO', 'fondo', 'fng.gov.co', 0, 'FNG. Principal fondo de garantías para créditos PYME en Colombia.'),
('SENA Fondo Emprender Cundinamarca', 'Coordinador Regional de Emprendimiento', 'EmprendimientoCundinamarca@sena.edu.co', 'CO', 'gobierno', 'fondoemprender.com', 0, 'SENA regional Cundinamarca. Fondo Emprender financia cientos de PYMEs/año.'),
('SENA Fondo Emprender Antioquia', 'Coordinador Regional de Emprendimiento', 'EmprendimientoAntioquia@sena.edu.co', 'CO', 'gobierno', 'fondoemprender.com', 0, 'SENA regional Antioquia. Fondo Emprender, fuerte penetración en PYMEs.'),
('MinCIT — Dirección MiPymes', 'Director Técnico de MiPymes', 'mipymes@mincit.gov.co', 'CO', 'gobierno', 'mipymes.gov.co', 0, 'Ministerio de Comercio Colombia. Directamente responsable de política PYME.'),
('Portafolio Colombia', 'Editor de Economía y Negocios', 'premios@portafolio.com.co', 'CO', 'medio', 'portafolio.co', 0, 'Diario económico líder de Colombia. Casa Editorial El Tiempo.'),
('Valora Analitik', 'Editor de Negocios y PYMEs', 'redaccion@valoraanalitik.com', 'CO', 'medio', 'valoraanalitik.com', 0, 'Portal de análisis económico y empresarial colombiano.'),
('Revista Dinero Colombia', 'Dirección Comercial', 'suscripciones@dinero.com', 'CO', 'medio', 'dinero.com', 0, 'Revista Dinero. Publicaciones Semana. Principal medio de negocios Colombia.'),

-- ── PERÚ ──
('CAMCO Piura', 'Presidente', 'camarapiura@camcopiura.org.pe', 'PE', 'camara', 'camcopiura.org.pe', 8000, 'Cámara de Comercio y Producción de Piura. Importante región norte del Perú.'),
('Cámara de Comercio La Libertad', 'Secretaría General', 'contacto@camaratru.org.pe', 'PE', 'camara', 'camaratru.org.pe', 12000, 'Cámara de Comercio y Producción de La Libertad — Trujillo.'),
('Cámara La Libertad — Comunicaciones', 'Comunicaciones', 'comunicaciones@camaralalibertad.org.pe', 'PE', 'camara', 'camaralalibertad.org.pe', 0, 'Contacto alternativo de Cámara de La Libertad.'),
('CCIA Arequipa', 'Secretario General', 'info@camara-arequipa.org.pe', 'PE', 'camara', 'camara-arequipa.org.pe', 15000, 'Cámara de Comercio e Industria de Arequipa. Segunda ciudad económica del Perú.'),
('CCLAM Lambayeque', 'Gerente General', 'gerencia@cclam.org.pe', 'PE', 'camara', 'cclam.org.pe', 8000, 'Cámara de Comercio y Producción de Lambayeque.'),
('Cámara de Comercio de Huancayo', 'Secretaría General', 'secretaria@cch.org.pe', 'PE', 'camara', 'cch.org.pe', 7000, 'Cámara de Comercio de Huancayo — Junín. Zona andina con alta actividad MYPE.'),
('Cámara de Comercio de Ica', 'Director Ejecutivo', 'lvila@camaraica.org.pe', 'PE', 'camara', 'camaraica.org.pe', 5000, 'Cámara de Comercio, Industria y Turismo de Ica.'),
('PERUCÁMARAS', 'Presidente', 'info@perucamaras.org.pe', 'PE', 'gremio', 'perucamaras.org.pe', 80000, 'Cámara Nacional de Comercio, Producción, Turismo y Servicios. Paraguas nacional.'),
('SNI Perú', 'Gerencia de Comercio Exterior', 'comercioexterior@sni.org.pe', 'PE', 'gremio', 'sni.org.pe', 25000, 'Sociedad Nacional de Industrias. Representación industrial PYME.'),
('ADEX Perú', 'Mesa de Partes', 'mesadepartes@adexperu.org.pe', 'PE', 'gremio', 'adexperu.org.pe', 10000, 'Asociación de Exportadores. Red de PYMEs exportadoras peruanas.'),
('Gremio PYME — CCL', 'Gerencia del Gremio', 'pempresa@camaralima.org.pe', 'PE', 'gremio', 'gremiopymes.pe', 15000, 'Gremio de la Pequeña Empresa de la Cámara de Comercio de Lima.'),
('ProInnóvate Perú', 'Coordinador de Programa Startup', 'startup@proinnovate.gob.pe', 'PE', 'gobierno', 'startup.proinnovate.gob.pe', 0, 'Entidad del Estado para innovación y emprendimiento PYME en Perú.'),
('ProInnóvate — Comunicaciones', 'Unidad de Comunicaciones', 'consultas@proinnovate.gob.pe', 'PE', 'gobierno', 'proinnovate.gob.pe', 0, 'Contacto general ProInnóvate. Programas de digitalización PYME.'),
('CIDE PUCP', 'Director del Centro', 'cide@pucp.edu.pe', 'PE', 'aceleradora', 'cide.pucp.edu.pe', 0, 'Centro de Innovación y Desarrollo Emprendedor — PUCP. Hub universitario.'),
('CDE ESAN', 'Coordinador General', 'cde@esan.edu.pe', 'PE', 'aceleradora', 'cde.esan.edu.pe', 0, 'Centro de Desarrollo Emprendedor de la Universidad ESAN.'),
('Revista Business Perú', 'Director Editorial', 'suscripciones@revistabusiness.com.pe', 'PE', 'medio', 'revistabusiness.com.pe', 0, 'Revista de negocios empresariales del Perú.'),
('Revista Emprender Perú', 'Editor', 'redaccion@emprender.pe', 'PE', 'medio', 'emprender.pe', 0, 'Medio especializado en emprendimiento y PYMEs peruanas.'),
('Emprender Perú — Publicidad', 'Director Comercial', 'publicidad@emprender.pe', 'PE', 'medio', 'emprender.pe', 0, 'Área comercial de Revista Emprender Perú.'),
('Actualidad Empresarial', 'Director Editorial', 'suscripciones@actualidadempresarial.pe', 'PE', 'medio', 'actualidadempresarial.pe', 0, 'Publicación especializada en contabilidad, tributación y gestión PYME.'),
('Mibanco Perú', 'Gerencia de Relaciones Institucionales', 'relacionesexternas@mibanco.com.pe', 'PE', 'fondo', 'mibanco.com.pe', 0, 'Principal banco de microfinanzas del Perú. Clientes directos son PYMEs.'),

-- ── ARGENTINA ──
('Cámara Argentina de Comercio y Servicios', 'Presidente', 'info@cac.com.ar', 'AR', 'camara', 'cac.com.ar', 500000, 'CAC. Cámara nacional de comercio. Una de las más grandes de Argentina.'),
('Cámara de Comercio de Córdoba', 'Presidente', 'recepcion@camcomcba.com.ar', 'AR', 'camara', 'camcomcba.com.ar', 40000, 'CCC. Cámara comercial de Córdoba. Segunda provincia empresarial de Argentina.'),
('FEDECOM Córdoba', 'Presidente Institucional', 'fedecom@fedecom.org.ar', 'AR', 'gremio', 'fedecom.org.ar', 20000, 'Federación Comercial de Córdoba. Red de cámaras del interior cordobés.'),
('FECOI Rosario', 'Presidenta', 'info@fecoi.org.ar', 'AR', 'gremio', 'fecoi.org.ar', 30000, 'Federación Gremial del Comercio e Industria de Rosario. PYMEs Santa Fe.'),
('Bolsa de Comercio de Rosario', 'Presidente', 'servicioalcliente@bcr.com.ar', 'AR', 'camara', 'bcr.com.ar', 15000, 'BCR. Institución referente del comercio y agro en Rosario.'),
('CECITYS Mendoza', 'Presidente Ejecutivo', 'cecitysmendoza@gmail.com', 'AR', 'camara', 'cecitys.org.ar', 12000, 'Cámara Empresaria de Comercio, Industria, Turismo y Servicios — Mendoza.'),
('FEBA Buenos Aires', 'Secretario General', 'secretaria@febaweb.org.ar', 'AR', 'gremio', 'febaweb.org.ar', 80000, 'Federación Económica de la Provincia de Buenos Aires. 80K PYMEs.'),
('UIPBA', 'Presidente', 'uipba@uipba.org.ar', 'AR', 'gremio', 'uipba.org.ar', 25000, 'Unión Industrial de la Provincia de Buenos Aires. PYMEs industriales.'),
('UIA Argentina', 'Director de Prensa', 'prensa@uia.org.ar', 'AR', 'gremio', 'uia.org.ar', 50000, 'Unión Industrial Argentina. Principal gremio industrial nacional.'),
('CAMARCO Argentina', 'Directora Ejecutiva', 'contacto@camarco.org.ar', 'AR', 'gremio', 'camarco.org.ar', 8000, 'Cámara Argentina de la Construcción. PYMEs del sector constructor.'),
('CACE Argentina', 'Director Ejecutivo', 'info@cace.org.ar', 'AR', 'camara', 'cace.org.ar', 5000, 'Cámara Argentina de Comercio Electrónico. E-commerce y PYMEs digitales.'),
('CESSI Argentina', 'Directora Ejecutiva', 'info@cessi.org.ar', 'AR', 'gremio', 'cessi.org.ar', 4000, 'Cámara de la Industria Argentina del Software. Ecosistema tech PYME.'),
('CIRA Argentina', 'Presidente', 'cira@cira.org.ar', 'AR', 'camara', 'cira.org.ar', 3000, 'Cámara de Importadores de la República Argentina.'),
('AEA Argentina', 'Presidente', 'info@aeanet.net', 'AR', 'gremio', 'aeanet.net', 0, 'Asociación Empresaria Argentina. Red de líderes y empresarios.'),
('Polo IT Buenos Aires', 'Presidente', 'polo@poloitbuenosaires.org.ar', 'AR', 'aceleradora', 'poloitbuenosaires.org.ar', 0, 'Hub de innovación tecnológica. Comunidad de empresas tech PYME de CABA.'),
('Wayra Argentina', 'Director de Hub', 'argentina@wayra.co', 'AR', 'aceleradora', 'wayra.com', 0, 'Aceleradora corporativa de Telefónica. Portafolio activo de startups.'),
('Kaszek Ventures', 'Managing Partner', 'contact@kaszek.com', 'AR', 'fondo', 'kaszek.com', 0, 'Principal fondo VC de LATAM. Invertido en Mercado Libre, Nubank y más.'),
('Alaya Capital Partners', 'Partner', 'carolina.costa@alaya-capital.com', 'AR', 'fondo', 'alaya-capital.com', 0, 'Fondo VC con base en Córdoba. Activo en etapa temprana Argentina.'),
('Newtopia VC', 'Socios Fundadores', 'hola@newtopia.vc', 'AR', 'fondo', 'newtopia.vc', 0, 'Fondo de venture capital especializado en founders argentinos.'),
('Subsecretaría PyME Córdoba', 'Subsecretario de PyME', 'comunicacion.comercio.pyme@gmail.com', 'AR', 'gobierno', 'cordobaproduce.cba.gov.ar', 0, 'Gobierno provincial Córdoba. Programas directos de apoyo a PyMEs.'),
('Subsecretaría Industria y PyMEs PBA', 'Subsecretario de Industria y PyMEs', 'contactoindustriapba@gmail.com', 'AR', 'gobierno', 'gba.gob.ar', 0, 'Provincia de Buenos Aires. Programas de digitalización PYME provinciales.'),
('Agencia I+D+i Argentina', 'Director de Convocatorias', 'convocatoria.aic@agencia.gob.ar', 'AR', 'gobierno', 'agencia.gob.ar', 0, 'ANPCyT. Financiamiento para innovación en empresas argentinas.'),
('iProfesional Argentina', 'Editor', 'publicidad@iprofesional.com', 'AR', 'medio', 'iprofesional.com', 0, 'Portal de negocios y economía. Gran audiencia empresarial en Argentina.'),
('El Cronista', 'Director Editorial', 'redaccion@cronista.com', 'AR', 'medio', 'cronista.com', 0, 'Diario económico especializado. Cobertura permanente de PYMEs.'),
('CESSI — Mercados Internacionales', 'Responsable de Mercados', 'mercados@cessi.org.ar', 'AR', 'gremio', 'cessi.org.ar', 0, 'Área internacional CESSI. Contacto alternativo para ecosistema tech PYME.'),

-- ── URUGUAY ──
('DINAPYME Uruguay', 'Director de DINAPYME', 'secretaria.dinapyme@miem.gub.uy', 'UY', 'gobierno', 'gub.uy', 0, 'Dirección Nacional de Artesanías, Pequeñas y Medianas Empresas. Ente rector PYME.'),
('ANDE Uruguay', 'Director Ejecutivo', 'ande@ande.org.uy', 'UY', 'gobierno', 'ande.org.uy', 0, 'Agencia Nacional de Desarrollo. Programas de apoyo e internacionalización PYME.'),
('Ingenio — Incubadora LATU', 'Directora', 'informes@latu.org.uy', 'UY', 'aceleradora', 'ingenio.org.uy', 0, 'Incubadora del Laboratorio Tecnológico del Uruguay. Principal hub de innovación.'),
('Uruguay Innovation Hub', 'Director del Hub', 'info@uruguayinnovationhub.uy', 'UY', 'aceleradora', 'uih.uy', 0, 'Hub de innovación empresarial Uruguay. Nexo entre startups y empresas.'),
('CUTI Uruguay', 'Secretario Ejecutivo', 'contacto@cuti.org.uy', 'UY', 'gremio', 'cuti.org.uy', 500, 'Cámara Uruguaya de Tecnologías de la Información. PYMEs tech.'),
('CAMBADU Uruguay', 'Gerente General', 'secretar@cambadu.com.uy', 'UY', 'gremio', 'cambadu.com.uy', 14000, 'Cámara de Bebidas, Alimentación y Afines. Red comercial PYME Uruguay.'),
('CAMTUR Uruguay', 'Presidencia', 'info@camtur.com.uy', 'UY', 'gremio', 'camtur.com.uy', 3000, 'Cámara Uruguaya de Turismo. PYMEs del sector turístico.'),
('APPCU Uruguay', 'Presidencia', 'appcu@appcu.org', 'UY', 'gremio', 'appcu.org', 1500, 'Asociación de Promotores Privados de Construcción. PYMEs constructoras.'),
('Cámara Mercantil Uruguay', 'Presidencia', 'info@camaramercantil.com.uy', 'UY', 'camara', 'camaramercantil.com.uy', 5000, 'Cámara Mercantil de Productos del País. Comercio agropecuario.'),
('ARU Uruguay', 'Presidente', 'membresia@aru.org.uy', 'UY', 'gremio', 'aru.org.uy', 4000, 'Asociación Rural del Uruguay. Red de productores y PYMEs agrícolas.'),
('CCIP Paysandú', 'Presidencia', 'info@ccipaysandu.com.uy', 'UY', 'camara', 'ccipaysandu.com.uy', 2000, 'Centro Comercial e Industrial de Paysandú. Interior del Uruguay.'),
('CCIS Salto', 'Presidente', 'ccisalto@ccisalto.com.uy', 'UY', 'camara', 'ccisalto.com.uy', 1800, 'Centro Comercial e Industrial de Salto. Segunda ciudad del Uruguay.'),
('CAMACOES Uruguay', 'Presidencia', 'camacoes@camacoes.org.uy', 'UY', 'camara', 'camacoes.org.uy', 1000, 'Cámara Española de Comercio en Uruguay. Empresas hispanouruguayas.'),
('Forbes Uruguay', 'Editor', 'editor@forbesuruguay.com', 'UY', 'medio', 'forbesuruguay.com', 0, 'Edición uruguaya de Forbes. Cobertura de negocios y emprendimiento.'),
('Crónicas Económicas Uruguay', 'Director', 'contacto@cronicas.com.uy', 'UY', 'medio', 'cronicas.com.uy', 0, 'Semanario económico. Principal medio de análisis empresarial del Uruguay.'),
('CIU — Comunicación', 'Gerencia de Comunicación', 'comunicacion@ciu.com.uy', 'UY', 'camara', 'ciu.com.uy', 5000, 'Contacto de comunicación de la Cámara de Industrias del Uruguay.')
ON CONFLICT (email) DO NOTHING;
